import { config as dotenvConfig } from "dotenv";

dotenvConfig();

export const {
  ENVIRONMENT,
  TYPEORM_CONNECTION,
  TYPEORM_HOST,
  TYPEORM_USERNAME,
  TYPEORM_PASSWORD,
  TYPEORM_DATABASE,
  TYPEORM_PORT,
  TYPEORM_LOGGING,
  TYPEORM_ENTITIES,
  TYPEORM_ENTITIES_DIR,
  TYPEORM_MIGRATIONS,
  TYPEORM_MIGRATIONS_DIR,
  SWAGGER_URL,
  SENTRY_DSN,
  PORT,
  JWT_SECRET,
  AWS_ACCESS_KEY,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  FROM_EMAIL,
  EMAIL_APP_PASSWORD,
  AWS_SES_API_VERSION,
  TIMEZONE,
  ADMIN_EMAIL,
} = process.env;
